### ISSUE TITLE
Вылет при запуске minecraft 1.19.4 quilt (0.19.0 beta17)

### ISSUE THREAD

**Issue by xXRinzlerrXx** [TheTarasus/RasusWaterfalls#1]
игра вылетает с такой ошибкой
![2023-06-09_19-58-18](https://github.com/TheTarasus/RasusWaterfalls/assets/135618265/422068e7-d569-4d53-a5ed-1a897a842791)

**Comment by TheTarasus** [comment]
> игра вылетает с такой ошибкой ![2023-06-09_19-58-18](https://user-images.githubusercontent.com/135618265/244757541-422068e7-d569-4d53-a5ed-1a897a842791.png)

Решение: установить новейшую версию Fabric/Quilt

**Comment by xXRinzlerrXx** [comment]
minecraft 1.19.4 fabric 0.14.21 (fabric api 0.83.0)

вылетает при работе с architectury-8.1.87-fabric и FactoryAPI-1.19.4-0.1.7-fabric

**Comment by TheTarasus** [comment]
Писать костыли, как в Water-Physics-Overhaul - я не собираюсь. Только ради водозаполняемых блоков превращать мой код в кучу говна, которое ещё и конфликтует с любыми другими модами - не собираюсь.

Так же, я не буду поддерживать совместимость с другими модами, которые написанны с использованием фреймворков - что означает, что у их авторов руки из жопы, и они ничего самостоятельно не могут написать.

Ещё, если не будет донатов - не ждите обновлений. Если этот мод будет несовместим с The Create, я ещё подумаю, потому что мне нужно, чтобы они не конфликтовали. Если будете донатить - хорошо, будут обновы.

Метать бисер перед свиньями за бесплатно я не собираюсь.

**Comment by xXRinzlerrXx** [comment]
да никто никого ничего не заставляет метать, так же как и никто никому ничего не должен
произошла проблема, о ней я отписал (отписал вам, так с другими модами такого не происходило и то-что дело в самих фреймворках я хз), но если такое дело "Так же, я не буду поддерживать совместимость с другими модами" вопросов нет
