### ISSUE TITLE
Вылет на 1.19.2

### ISSUE THREAD

**Issue by lomovoyPlayer** [TheTarasus/RasusWaterfalls#2]
Для начала скажу, что даже запустил игру я не сразу, т.к.  загрузчик ругается на несоответствие версий, хотя всё правильно, так что я в настройках мода указал конкретно 1.19.2
Вот логи, у меня очень много модов в сборке, так что это вероятно конфликт с одним из них
[latest.log](https://github.com/TheTarasus/RasusWaterfalls/files/11787273/latest.log)

**Comment by TheTarasus** [comment]
Логи пишут НИ-ХРЕ-НА. У тебя сборка из 500+ модов(логи так говорят). Ты понимаешь, что ты пытался впихнуть невпихуемое? Что я тебе должен ответить?

Я написал охрененный мод на физику воды, который не лагает. Я не получил за него ни копейки. Если ты думаешь, что я буду разбираться в этом болоте, гуглить каждый отдельный мод, ставить их себе на компьютер, с условием того, что curseforge и modrinth недавно подвергались заражениям вирусами, и как конченный разбираться в этом - ты глубоко заблуждаешься.

Я за вами, малышами, подтирать попку не собираюсь. Если ты хочешь запустить сборку на 500 модов - сам её и отлаживай, убирай-добавляй все моды по отдельности, надрывай свою голову и задницу самостоятельно.

Так как я нихера не получу за то, что разберусь со всеми конфликтами из этого бесчисленного количества модов - просьба исчезнуть и никогда не появляться. Ты мне нихера не заплатишь, и выставляешь умалишённую задачу, связанную с твоей глупостью. Решай свои проблемы сам.

Если ты качаешь 500 модов - задумайся о смысле своего существования, извращенец. Удали Minecraft, и езжай к бабушке на дачу, или в летний лагерь.
