### ISSUE TITLE
1.19.2 без других модов, только фабрик

### ISSUE THREAD

**Issue by lomovoyPlayer** [TheTarasus/RasusWaterfalls#3]
[latest.log](https://github.com/TheTarasus/RasusWaterfalls/files/11795558/latest.log)
Как вы и сказали, я сам проверил, вырезав банально всё. Игра всё равно вылетает.

P.S. В прошлый раз ты меня оскорбил, но я всё равно решил помочь, т.к. у вас действительно великолепная модификация. И если уж тебя человек взбесил, не трать время на придумывание оскорблений.

**Comment by TheTarasus** [comment]
Ты поставил версию 1.19.2,
А нужно 1.19.4, никакая другая!

Даже в патчах Minecraft изменяются названия классов, методов и всего подобного, потому что с каждым обновлением код заново обфусцируется. Для начала, составляй грамонтый Issues, и только потом можешь долбить мозги разработчикам.

Я уже своё отпатчил, своё отработал, затрахал себе мозги, пока всё это писал, и потерял 15 кг своего веса. Пока донатов не будет - я ничего делать не собираюсь, даже выпускать какие-то новые моды или обновы. И никакой другой мододел не станет писать код, если ему это не приносит шекели. Вопросы?

**Comment by lomovoyPlayer** [comment]
И сколько же ты хочешь за перенос с 1.19.4 на 1.19.2? 
Хотя у тебя везде написано 1.19.Х за исключением самого файла мода 
![image](https://github.com/TheTarasus/RasusWaterfalls/assets/102898719/65a5ac2e-6080-4b15-bcd5-c6f92617dd81)

**Comment by TheTarasus** [comment]
Я хочу столько, сколько мне с запасом хватит на:
1. Восстановление моего веса (+15 кг) 
2. Прибавление моего дополнительного веса (ещё +15 кг).

Получаем 50(текущий вес) + 15 + 15 = 80 кг целевого веса. У меня метаболизм такой же быстрый, как и у ласки.

Мой рост составляет 184 сантиметра.
Я и так был дрищём без жира, но во мне хотя бы мышцы были. А теперь - кожа, да кости. И тратить массу своего тела за то, чтобы тебя и дальше заставляли работать без оплаты - я не собираюсь.

Если такая тема продолжится, то есть - не будут кидать донаты и дальше будут просить о поддержке мода: я мало того, что не буду исправлять ошибки, но и ещё какую-нибудь подлянку придумаю, которая уже сможет с вас, свиней, стрясти деньги. И да, мод всё ещё будет бесплатным, но по крайней мере, с вас он поимеет денег.

Лохом я оставаться не собираюсь. Пока что, я уеду на природу, потом вернусь и посмотрю - сколько навара вы мне принесли.

Если на donationalerts будет как и сейчас - нихрена, то и вы ничего хорошего не ждите.
